[package]
name = "shibboleth-oauth2-forward"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "0.4"
simplelog = "0.10"
oxide-auth = "0.5"
actix-web = "3"
thiserror = "1"

[dev-dependencies]
actix-rt = "2"