[package]
edition = "2018"
name = "shibboleth-oauth2-forwarding"
version = "0.1.0"
license = "Apache-2.0"
repository = "https://github.com/korpling/shibboleth-oauth2-forwarding"
authors = ["Thomas Krause"]

[dependencies]
actix-web = "3"
actix-web-actors = "3"
log = "0.4"
oxide-auth = "0.5"
oxide-auth-async = "0.1"
oxide-auth-actix = "0.1"
simplelog = "0.10"
thiserror = "1"
url = "2"

[dev-dependencies]
actix-rt = "2"
serde = {version="1", features = ["derive"]}
serde_json = "1"