sign-commit = true
sign-tag = true
dev-version-ext = "dev"
no-dev-version = true
pre-release-hook = ["scripts/pre_release.sh"]
tag-name =  "v{{version}}"
pre-release-replacements = [
    { file = "../CHANGELOG.md", search = "## \\[Unreleased\\]", replace = "## [Unreleased]\n\n## [{{version}}] - {{date}}" },
    { file = "../CITATION.cff", search = "version: [0-9.]+", replace = "version: {{version}}" },
    { file = "../CITATION.cff", search = "date-released: [0-9\\-]+", replace = "date-released: {{date}}" }
]