[mapping]
include_headers = ["x-admin"]
token_template = "examples/annis-token-template.json"
default_sub = "academic"

[client]
id = "ANNIS"
redirect_uri = "http://localhost:5712"

[client.token_verification]
type = "HS256"
secret = "random-words-are-not-secure-please-change-me"
