name: Automated tests
on: push
jobs:
  test_linux:
    name: Execute automated tests on Ubuntu Linux
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          profile: minimal
      - run: cargo build --all-features --verbose
      - run: cargo test --all-features --verbose
  test_windows:
    name: Execute automated tests on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          profile: minimal
      - run: cargo build --all-features --verbose
      - run: cargo test --all-features --verbose
  test_mac:
    name: Execute automated tests on OSX
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          profile: minimal
      - run: cargo build --all-features --verbose
      - run: cargo test --all-features --verbose
